version: '3'
services:
  postgres:
    image: clkao/postgres-plv8:12-2
    restart: always
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
