version: '3'
services:
  postgres:
    # can't update to 12 until https://github.com/clkao/docker-postgres-plv8/issues/36 is fixed
    image: clkao/postgres-plv8:12-2
    restart: always
    ports:
    - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
